import pytest
from camel_tools.disambig.common import Disambiguator

from rules.transliterate import transliterate, _get_disambiguator


@pytest.fixture()
def disambiguator():
    return _get_disambiguator("msa", "calima-msa-s31")

class TestTransliterate:

    @pytest.mark.parametrize("text,transliteration", [
        # characters
        ("ا", "a"),
        ("ب", "b"),
        ("ت", "t"),
        ("ث", "t"),
        ("ج", "ġ"),
        ("ح", "ħ"),
        ("خ", "ħ"),
        ("د", "d"),
        ("ذ", "D"),
        ("ر", "r"),
        ("ز", "ż"),
        ("ش", "x"),
        ("ص", "s"),
        ("ض", "d"),
        ("ط", "t"),
        ("ظ", "d"),
        ("ع", "'"),
        ("غ", "'"),
        ("ق", "q"),
        ("ك", "k"),
        ("ل", "l"),
        ("م", "m"),
        ("ن", "n"),
        ("ه", "h"),
        ("و", "u"),
        ("ي", "i"),
        ("،", ","),
        ("؛", ";"),
        ("؟", "?"),
        ("٪", "%"),
        ("٠", "0"),
        ("١", "1"),
        ("٢", "2"),
        ("٣", "3"),
        ("٤", "4"),
        ("٥", "5"),
        ("٦", "6"),
        ("٧", "7"),
        ("٨", "8"),
        ("٩", "9"),
        # common words
        ("بيت", "bejt"),
        ("عصفور", "għusfur"),
        ("اسم", "ism"),
        ("ليل", "lejl"),
        ("واحد", "waħid"),
        ("عربي", "għerebi"),
        ("يومين", "jewmejn"),
        # sentences
        ("كلمات مالطية.", "kelimiet maltijja."),
        ("كيف أنت؟", "kejfe ante?"),
        # proper nouns
        ("مالطا", "Malta"),
        ("إنجلترا", "Anġiltira"),
        ("الفاتيكان", "il-Fatikan"),
        # ta-marbuta
        ("كتابة المرأة", "kitabt il-mera"),
        # sun letter allomorphy assimilation
        ("الكلب", "il-kelb"),
        ("الليل", "il-lejl"),
        ("الدار", "id-dar"),
        ("النحلة", "in-neħla"),
        ("الرابع", "ir-rabi'"),
        ("السيارة", "is-sejjara"),
        ("التفاحة", "it-tuffaħa"),
        ("الشوك", "ix-xewk"),
        ("الزيت", "iż-żejt"),
        # li+il-
        ("للكلب", "lill-kelb"),
        # ("لللون", "lil-lejl"),
        ("للدار", "lid-dar"),
        ("للنحلة", "lin-neħla"),
        ("للرابع", "lir-rabi'"),
        ("للسيارة", "lis-sejjara"),
        ("للتفاحة", "lit-tuffaħa"),
        ("للشوك", "lix-xewk"),
        ("للزيت", "liż-żejt"),
        # bi+il-
        ("بالكلب", "bil-kelb"),
        ("بالليل", "bil-lejl"),
        ("بالدار", "bid-dar"),
        ("بالنحلة", "bin-neħla"),
        ("بالرابع", "bir-rabi'"),
        ("بالسيارة", "bis-sejjara"),
        ("بالتفاحة", "bit-tuffaħa"),
        ("بالشوك", "bix-xewk"),
        ("بالزيت", "biż-żejt"),
        # bħal
        ("بحال", "bħal"),
        # bħal+il-
        ("بحال الكلب", "bħall-kelb"),
        ("بحال الليل", "bħal-lejl"),
        ("بحال الدار", "bħad-dar"),
        ("بحال النحلة", "bħan-neħla"),
        ("بحال الرابع", "bħar-rabi'"),
        ("بحال السيارة", "bħas-sejjara"),
        ("بحال التفاحة", "bħat-tuffaħa"),
        ("بحال الشوك", "bħax-xewk"),
        ("بحال الزيت", "bħaż-żejt"),
        # fi+il-
        ("في الكلب", "fil-kelb"),
        ("في الليل", "fil-lejl"),
        ("في الدار", "fid-dar"),
        ("في النحلة", "fin-neħla"),
        ("في الرابع", "fir-rabi'"),
        ("في السيارة", "fis-sejjara"),
        ("في التفاحة", "fit-tuffaħa"),
        ("في الشوك", "fix-xewk"),
        ("في الزيت", "fiż-żejt"),
        # ma'+il-
        ("مع الكلب", "mal-kelb"),
        ("مع الليل", "mal-lejl"),
        ("مع الدار", "mad-dar"),
        ("مع النحلة", "man-neħla"),
        ("مع الرابع", "mar-rabi'"),
        ("مع السيارة", "mas-sejjara"),
        ("مع التفاحة", "mat-tuffaħa"),
        ("مع الشوك", "max-xewk"),
        ("مع الزيت", "maż-żejt"),
        # ta'+il-
        ("تاع الكلب", "tal-kelb"),
        ("تاع الليل", "tal-lejl"),
        ("تاع الدار", "tad-dar"),
        ("تاع النحلة", "tan-neħla"),
        ("تاع الرابع", "tar-rabi'"),
        ("تاع السيارة", "tas-sejjara"),
        ("تاع التفاحة", "tat-tuffaħa"),
        ("تاع الشوك", "tax-xewk"),
        ("تاع الزيت", "taż-żejt"),
        # għal+il-
        ("على الكلب", "għall-kelb"),
        ("على الليل", "għal-lejl"),
        ("على الدار", "għad-dar"),
        ("على النحلة", "għan-neħla"),
        ("على الرابع", "għar-rabi'"),
        ("على السيارة", "għas-sejjara"),
        ("على التفاحة", "għat-tuffaħa"),
        ("على الشوك", "għax-xewk"),
        ("على الزيت", "għaż-żejt"),
        # minn+il-
        ("من الكلب", "mill-kelb"),
        ("من الليل", "mil-lejl"),
        ("من الدار", "mid-dar"),
        ("من النحلة", "min-neħla"),
        ("من الرابع", "mir-rabi'"),
        ("من السيارة", "mis-sejjara"),
        ("من التفاحة", "mit-tuffaħa"),
        ("من الشوك", "mix-xewk"),
        ("من الزيت", "miż-żejt"),
    ])
    def test_transliterate(self, disambiguator: Disambiguator, text: str, transliteration: str):
        assert transliterate(text, disambiguator) == transliteration
